version: '3'
services:
 mongodb:
   image : mongo
   restart: always
   ports:
     - "27016:27016"
   container_name: mongo-container
   network_mode: host
 spring:
   image: spring-boot
   restart: always
   build:
     MusixMongoDB/
   container_name: spring-docker
   network_mode: host
   ports:
     - 8090:8090
   expose:
     - 8090
 zuul:
   image: zuul
   restart: always
   build:
     zull/
   container_name: zuul-container
   network_mode: host
   ports:
     - 8060:8060
   expose:
     - 8060

 config-server:
    container_name: config-server
    image: hyness/spring-cloud-config-server
    ports:
      - 8888:8888
    volumes:
      - ./config:/config
    environment:
      - BANNER_LOCATION=file:/config/banner.txt

 eureka-peer1:
    build:
      eureka/
    image: eureka-server-tpd
    container_name: eureka-peer1
    environment:
      - SPRING_PROFILES_ACTIVE=peer1
      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
    ports:
      - 8761:8761
    network_mode: host

 
